优化 github action

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -9,7 +9,6 @@ jobs:
   deploy:
     runs-on: ubuntu-latest
     timeout-minutes: 60
-
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
@@ -35,7 +34,6 @@ jobs:
             echo "======================================="
             printf '%s\n' "${{ secrets.ENV_FILE_CONTENT }}" > .env
             echo "[INFO] ✅ .env written."
-
 
             cd /home/lxt/project/tech-backend
 
@@ -76,19 +74,19 @@ jobs:
 
             # Check for any Restarting
             if docker compose ps | grep -q "Restarting"; then
-            echo
-            echo "[ERROR] ❌ One or more containers are Restarting!"
-            docker compose logs --tail=50
-            exit 1
+              echo
+              echo "[ERROR] ❌ One or more containers are Restarting!"
+              docker compose logs --tail=50
+              exit 1
             fi
 
             # Check that all containers are Up
             if docker compose ps | grep -v "Up" | grep -v "NAME" | grep -v "-----" | grep .; then
-            echo
-            echo "[ERROR] ❌ One or more containers are not Up!"
-            docker compose ps
-            docker compose logs --tail=50
-            exit 1
+              echo
+              echo "[ERROR] ❌ One or more containers are not Up!"
+              docker compose ps
+              docker compose logs --tail=50
+              exit 1
             fi
 
             echo
